// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaF4ckXudkdBNmYuIGfMPOoJkLoCrrR4Y',
    appId: '1:514591237973:android:3674a0176316645e98f1dc',
    messagingSenderId: '514591237973',
    projectId: 'swwisho-45670',
    databaseURL: 'https://swwisho-45670-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swwisho-45670.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnCtXrQjsyeBy_wYUkZiP3sSHtTCot9Zo',
    appId: '1:514591237973:ios:73a872da51b0d9f098f1dc',
    messagingSenderId: '514591237973',
    projectId: 'swwisho-45670',
    databaseURL: 'https://swwisho-45670-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swwisho-45670.firebasestorage.app',
    androidClientId: '514591237973-33emk9pcvolahkcta0avcc0hl41pj11r.apps.googleusercontent.com',
    iosClientId: '514591237973-dgetu3542ajdr14qd4o7honahu6tdd6n.apps.googleusercontent.com',
    iosBundleId: 'com.pt.swwishoprovider',
  );
}
